In [ ]:
#Setup
import collections
import pandas as pd
import numpy as np
import spacy
import pickle
from spacy.tokens import DocBin
from spacy.tokens import Doc
nlp = spacy.load('en_core_web_md')

import matplotlib.pyplot as plt
import squarify
import seaborn as sns
plt.rcParams["figure.figsize"] = [20,10]

#Set sentiment extensions
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sent_analyzer = SentimentIntensityAnalyzer()
def sentiment_scores(docx):
    return sent_analyzer.polarity_scores(docx.text)
Doc.set_extension("sentimenter",getter=sentiment_scores,force=True)

In [ ]:
#Trump became the president as of January 20, 2017, but here we extract all the tweets as of 2007.
#Also we need to remove retweets
df1 = pd.read_excel('tweets.xls')
df1 = df1.iloc[:11007]
df1 = df1[df1['is_retweet'] == False]
df1 = df1.drop(['id_str', 'is_retweet'], axis=1)
df1.to_excel('tweets_new.xls', index=False)

In [ ]:
#Apply NLP models on the remaining tweets
df1 = pd.read_excel('tweets_new.xls')
tweets = df1['text']

doc_bin = DocBin(attrs=['LEMMA', 'ENT_IOB', 'ENT_TYPE', 'is_digit', 'like_url', 'like_num', 
                        'DEP', "POS", 'TAG', 'SHAPE', 'is_alpha', 'is_stop', 'is_oov'], store_user_data=True)

for doc in nlp.pipe(tweets):
    doc_bin.add(doc)
bytes_data = doc_bin.to_bytes()

#Save to a pickle file
pickle.dump(bytes_data, open('tweets_new.p', 'wb'))

In [70]:
#A help function to read the pickle file
def read_data(path):
    tweets = pickle.load(open(path, 'rb'))
    doc_bin = DocBin().from_bytes(tweets)
    docs = list(doc_bin.get_docs(nlp.vocab))
    return docs
#read_data('tweets_new.p')

In [27]:
#Hourly SP 500 Data as of 2007
#I combine two source files together, one for 2017 and the other for 2018 and after.
df2 = pd.read_excel('S&P 500_new.xls', parse_dates=True, index_col=0)

                        Open     High      Low    Close
2017-01-02 18:30:00  2241.00  2244.50  2241.00  2243.00
2017-01-02 19:30:00  2242.75  2242.75  2240.25  2241.00
2017-01-02 20:30:00  2241.25  2242.75  2240.00  2242.50
2017-01-02 21:30:00  2242.25  2243.75  2242.00  2243.50
2017-01-02 22:30:00  2243.75  2244.50  2243.50  2244.50
2017-01-02 23:30:00  2244.25  2244.75  2244.00  2244.75
2017-01-03 00:30:00  2244.50  2247.25  2244.50  2246.25
2017-01-03 01:30:00  2246.00  2247.50  2245.75  2247.50
2017-01-03 02:30:00  2247.75  2249.25  2247.50  2248.75
2017-01-03 03:30:00  2249.00  2251.25  2248.25  2250.75
2017-01-03 04:30:00  2250.50  2250.50  2248.00  2249.75
2017-01-03 05:30:00  2250.00  2250.75  2249.50  2250.50
2017-01-03 06:30:00  2250.75  2254.50  2250.50  2253.75
2017-01-03 07:30:00  2254.00  2255.00  2252.25  2253.25
2017-01-03 08:30:00  2253.00  2253.25  2250.25  2251.25
2017-01-03 09:30:00  2251.50  2253.75  2248.00  2250.50
2017-01-03 10:30:00  2250.75  2259.25  2246.75  2247.50
2017-01-03 11:30:00  2247.25  2248.25  2239.25  2243.75
2017-01-03 12:30:00  2244.00  2244.75  2239.75  2242.75
2017-01-03 13:30:00  2242.50  2244.00  2239.75  2240.50
2017-01-03 14:30:00  2240.75  2244.25  2240.50  2243.75
2017-01-03 15:30:00  2244.00  2251.50  2242.50  2250.75
2017-01-03 16:30:00  2251.00  2252.75  2251.00  2252.25
2017-01-03 17:30:00      NaN      NaN      NaN      NaN
2017-01-03 18:30:00  2252.75  2252.75  2251.00  2252.00
2017-01-03 19:30:00  2251.75  2253.50  2251.25  2253.00
2017-01-03 20:30:00  2253.25  2254.50  2253.00  2254.25
2017-01-03 21:30:00  2254.00  2254.50  2253.75  2254.25
2017-01-03 22:30:00  2254.50  2255.25  2254.00  2255.00
2017-01-03 23:30:00  2255.25  2255.50  2254.50  2255.50
...                      ...      ...      ...      ...
2019-10-25 14:30:00  3021.59  3023.68  3018.56  3022.47
2019-10-25 15:30:00  3022.59  3024.07  3020.79  3021.78
2019-10-28 09:30:00  3034.04  3042.92  3033.99  3042.13
2019-10-28 10:30:00  3042.12  3044.08  3037.27  3038.60
2019-10-28 11:30:00  3038.59  3041.21  3036.47  3040.37
2019-10-28 12:30:00  3040.17  3040.17  3037.54  3039.74
2019-10-28 13:30:00  3039.74  3041.25  3038.74  3040.20
2019-10-28 14:30:00  3040.22  3042.56  3039.98  3042.42
2019-10-28 15:30:00  3042.42  3042.57  3039.02  3039.12
2019-10-29 09:30:00  3035.39  3042.06  3034.81  3041.12
2019-10-29 10:30:00  3041.17  3047.87  3040.18  3043.78
2019-10-29 11:30:00  3043.82  3045.10  3036.24  3044.68
2019-10-29 12:30:00  3045.50  3045.82  3043.18  3043.31
2019-10-29 13:30:00  3043.33  3044.79  3039.55  3040.18
2019-10-29 14:30:00  3040.21  3040.89  3036.71  3037.99
2019-10-29 15:30:00  3037.99  3038.54  3035.33  3036.31
2019-10-30 09:30:00  3040.42  3040.42  3025.96  3034.51
2019-10-30 10:30:00  3034.48  3036.52  3032.11  3033.61
2019-10-30 11:30:00  3033.65  3036.50  3030.99  3036.01
2019-10-30 12:30:00  3036.12  3037.19  3034.10  3034.75
2019-10-30 13:30:00  3034.74  3038.90  3028.51  3035.86
2019-10-30 14:30:00  3035.87  3050.10  3030.78  3047.36
2019-10-30 15:30:00  3047.30  3047.95  3044.16  3047.40
2019-10-31 09:30:00  3046.51  3046.51  3028.42  3029.93
2019-10-31 10:30:00  3029.94  3035.39  3023.19  3031.83
2019-10-31 11:30:00  3031.83  3034.55  3026.78  3029.51
2019-10-31 12:30:00  3029.49  3030.60  3024.33  3030.32
2019-10-31 13:30:00  3030.39  3032.03  3025.87  3028.85
2019-10-31 14:30:00  3028.86  3032.39  3024.18  3029.85
2019-10-31 15:30:00  3029.86  3038.66  3029.29  3038.05

[11875 rows x 4 columns]